---
- name: Create an Ec2 instance using ansible
  hosts: localhost
  connection: local
  tasks: 
    - name: Launch Ec2 instance
      ec2:
        key_name: my-key
        instance_type: t2.micro
        image: ami-026b57f3c383c2eec
        wait: yes
        count: 1
        vpc_subnet_id: subnet-0048c07c9e12ea564
        assign_public_ip: yes
        region: us-east-1
        aws_access_key: AKIAQZV5L4URBKHKDEG3
        aws_secret_key: 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 